### ISSUE TITLE
not works with Dream Machine Pro

### ISSUE THREAD

**Issue by patrick-dmxc** [Isaksson/node-red-contrib-unifi#19] opened 2020-03-02 20:17 UTC
Its not working with the new Dream Machine Pro. it seems the authentification has changed

**Comment by michaltaberski** [comment] 2020-03-12 13:08
Ok, thanks for info. At least I know it doesn't make sense to play more with it.

**Comment by Isaksson** [comment] 2020-03-18 10:28
I do not have a Dream Machine I run the controller on a server.
When using Dream Machine does the controller need to communicate to the cloud with ubnt?

Do you need to login with something else than just local username and password?

**Comment by patrick-dmxc** [comment] 2020-03-18 18:13
no, the protocol has changed

**Comment by Isaksson** [comment] 2020-03-18 18:29
Ahh okey, that's really bad from ubnt, then they use a different controller software on that device.

**Comment by Isaksson** [comment] 2020-03-23 15:06
I have now pushed a new version to NPM (0.1.0) please try this version against the Dream Machine Pro, you just have to check the checkbox Unifi OS on this node.
![unifios](https://user-images.githubusercontent.com/4119080/77330914-4ad3d880-6d20-11ea-8692-fc9c1a6aa056.PNG)

**Comment by patrick-dmxc** [comment] 2020-03-23 19:46
I tested it, but nothing hapend. There is nothin come out of the Unifi Node.
maybe i use the wrong IP.
which on is the Controler IP?
I have 3 VLANs where i can reach the Controler with the Browser.
Management 192.168.178.20
Private 192.168.1.1
SmartDevices 192.168.10.1 (Node Red is in this VLAN)

all three VLANs ar able to reach each other

**Comment by michaltaberski** [comment] 2020-03-23 19:57
If you are in a LAN you should use IP of the gateway. Most likely `192.168.1.1`.

Nevertheless I am doing so, but I am getting no response from the node - nor error neither. 

Also I am pushing following message to the node:
```
return {
    payload: { command: "ClientDevices"}
};
```

without result.

**Comment by Isaksson** [comment] 2020-03-23 21:51
Thanks for the test, and you get non error message in Node-REDs output?
I do not have any device to test against so that makes this a little harder.
But I was pretty sure that this should have worked.

Do you get any output at all from the Node? If you enter incorrect login details does that generate error message?

**Comment by Isaksson** [comment] 2020-03-23 21:54
And please try this command "SiteStats" from the drop down menu, and when you do, do not inject any command.

**Comment by Isaksson** [comment] 2020-03-24 09:27
New version 0.1.1 is now pushed to NPM, maybe I have solved the login issue with this fix.

**Comment by patrick-dmxc** [comment] 2020-03-24 11:04
You only changed the VersionNumber ;)

**Comment by Isaksson** [comment] 2020-03-24 13:05
I did two pushes, first the change in .js and then I did the version number change for NPM to work :)

**Comment by patrick-dmxc** [comment] 2020-03-24 18:01
Ok, i‘ve tested this, but Nothing, no Log, no exception. 
Maybe ist because  ist runs on iobroker?

**Comment by Isaksson** [comment] 2020-03-24 18:29
So you run your Node-RED in the cloud? do you have access to your dream machine pro from internet?

**Comment by patrick-dmxc** [comment] 2020-03-24 19:34
Node Red runs on ioBroker
IoBroker runns on RaspberryPi and is in my local Network and has access to the UDM Pro.

**Comment by Isaksson** [comment] 2020-03-25 11:24
Then that should not be any issue, as long as you enters the correct IP address for your controller and that its reachable from the Raspberry network

**Comment by pettaflex** [comment] 2020-03-25 15:37
Hi.

Tried on both a raspberry pi installation and on a pc running latest ubuntu.
And neither of 1.0 and 1.1 is working for me!
Was working on a older version.
Not using dreammachine but unifi controller on another raspberry!

**Comment by Isaksson** [comment] 2020-03-25 17:53
> Hi.
> 
> Tried on both a raspberry pi installation and on a pc running latest ubuntu.
> And neither of 1.0 and 1.1 is working for me!
> Was working on a older version.
> Not using dreammachine but unifi controller on another raspberry!

I have created a new issue about this.

**Comment by michaltaberski** [comment] 2020-03-25 21:34
I have Raspberry PI setup with Node-Red running on docker + UDM Pro as a main router. 

<img width="543" alt="Node-RED : 192 168 1 10 2020-03-25 22-32-48" src="https://user-images.githubusercontent.com/202033/77587665-a781ef80-6ee8-11ea-90e1-df6537295c90.png">

Nothing happens, no errors, no logs. If I can help you debug the issue let me know.

**Comment by Isaksson** [comment] 2020-03-26 07:08
New version published to NPM.

**Comment by michaltaberski** [comment] 2020-03-26 07:25
Now it looks like this:

<img width="313" alt="Screenshot 2020-03-26 at 08 25 09" src="https://user-images.githubusercontent.com/202033/77620747-551dee80-6f3b-11ea-9bc7-72639dbc786a.png">


But still I don't know how to log error in order to give some more valuable info.

**Comment by Isaksson** [comment] 2020-03-26 08:02
I have made some big changes to this Node witch now gives me the possibility to make mush better error handling, as you could see I have not yet implemented this :)
If I just should make a guess then I would say that this error message is a connection timeout against the IP address added as controller IP.

I dont know how you "start" Node-RED but Iam running it in a CMD in windows environment so I see the console output like this
![noderedlog](https://user-images.githubusercontent.com/4119080/77623512-7f25df80-6f40-11ea-997d-48903fedf10f.PNG)

**Comment by michaltaberski** [comment] 2020-03-26 08:38
Interesting `ERROR: Error: connect ECONNREFUSED 192.168.1.1:8443`

**Comment by Isaksson** [comment] 2020-03-26 08:45
Does the UDM Pro uses different port then 8443?
The error message tells us that it does not accept connection on that port.
This is how it will look like in next version, added error to Node
In this example I have changed to a port on my server that does not accept connection.

![noderederror](https://user-images.githubusercontent.com/4119080/77627029-864fec00-6f46-11ea-9b38-22123d8ffe71.PNG)

**Comment by michaltaberski** [comment] 2020-03-26 08:50
> Does the UDM Pro uses different port then 8443?

Good question, not sure if there is public API documentation regarding this matter.

Looking forward to see updated error messaging 👍

**Comment by Isaksson** [comment] 2020-03-26 09:13
~~I have not seen any indication that they should have changed that port so I think 8443 is the correct one.~~
Are you sure that you are connecting against the correct IP? maybe the UDM Pro has multiple IP address and only one that accept remote connection?

**Comment by Isaksson** [comment] 2020-03-26 09:15
I found one post that is 1 month old and they did run against port 443 on their UDM Pro, so please try that.

**Comment by patrick-dmxc** [comment] 2020-03-26 12:03
Port 443 works.

**Comment by Isaksson** [comment] 2020-03-26 13:32
> Port 443 works.

Great, have you confirmed that it works to login and also to execute some commands against the UDM Pro?

**Comment by patrick-dmxc** [comment] 2020-03-26 19:41
Yes, it works, except "AllUsers".
the message payload is empty

**Comment by patrick-dmxc** [comment] 2020-03-26 19:52
DisableWlan not works

**Comment by Isaksson** [comment] 2020-03-26 21:02
Thanks.
I have created a new Issue with a list of commands that is not working with Unifi OS, I have added AllUsers and DisableWlan to that list, I will check this tomorrow.
Iam closing this issue now.

**Closed as completed by Isaksson** 2020-03-26 21:02 UTC
Labels: enhancement

**Comment by michaltaberski** [comment] 2020-03-28 18:33
True,  we  are one step further. If I don't select `Unifi OS` the node  is  showing green status `OK`.

If I select Unifi OS checkbox I am getting following issues:

<img width="669" alt="Screenshot 2020-03-26 at 13 31 30" src="https://user-images.githubusercontent.com/202033/77647248-5ca6bd00-6f66-11ea-9712-5f918fdbd073.png">

<img width="1435" alt="Screenshot 2020-03-26 at 13 31 43" src="https://user-images.githubusercontent.com/202033/77647274-68927f00-6f66-11ea-8f6a-e577f2d439d9.png">

**Comment by michaltaberski** [comment] 2020-03-28 18:41
Works, thanks!

**Comment by Isaksson** [comment] 2020-04-07 16:53
@patrick-dmxc I have made an adjustment for the command DisableWlan for UnifiOS could you please test this new version, its on NPM 0.1.4, please respond in the issue #23
