### ISSUE TITLE
DEPTH_ZERO_SELF_SIGNED_CERT

### ISSUE THREAD

**Issue by MvQuast** [Isaksson/node-red-contrib-unifi#106] opened 2023-07-18 14:13 UTC
Hi,
since upgrade to 0.2.14, my UNIFI nodes are no longer working, failing to login within Home Assistant, using local IP address.
I've never enabled SSL verification, but it still fails.

Thx,
Marcel

**Comment by Isaksson** [comment] 2023-07-21 20:18
Hello.
Have you tried uninstall and then install of this node, maybe something failed during the upgrade.

**Comment by MvQuast** [comment] 2023-07-22 13:13
I saved my flows containing UNIFI modules, removed them, restarted NR - uninstalled your modules - again restart NR - then reinstalled 0.2.14, reimported my old flow
error remains, unfortuntely there's no way back to any previous version

**Comment by Isaksson** [comment] 2023-07-24 10:25
This is a strange error, its the same issue as in #100 and I connected to that users Unifi environment and it worked for me without any issue.
So it has to be some other factor that is causing this.

I have tried many different installations with many versions.
Could you write your versions of software and what hardware you run this on.

The only way for me to reproduce this error is to enable the "SSL Verification"

By the way, have you tried to create a new Unifi configuration?

**Comment by MvQuast** [comment] 2023-07-25 07:26
I found the module causing this issue: node-red-contrib-tibber-api
As soon as this is installed, you'll get the error. Uninstall and restart NR will repair it.

**Comment by Isaksson** [comment] 2023-07-25 08:04
Great work finding this, that's the reason that I could not reproduce the error in my setups.I released a new version yesterday where I bumped the dependencies to later versions.Maybe that could solve the issue.But now, with your help I will install that node and see if I could fix this issue.

**Comment by Isaksson** [comment] 2023-07-25 09:09
Just verified that I get the same error as soon as I install node-red-contrib-tibber-api I have not configured that Node just installed it.

**Comment by PowerZone21** [comment] 2023-08-04 04:42
Great work guys.
Thats tre reason causing ny problem also.
Looking forward to a solution🤪

**Comment by Isaksson** [comment] 2023-08-09 13:58
I have created an issue a couple of weeks ago over at node-red-contrib-tibber-api GitHub, but have not yet received any response
https://github.com/bisand/node-red-contrib-tibber-api/issues/86

**Comment by PowerZone21** [comment] 2023-08-13 00:02
Hi,

Is it possible to learn how to disable the thread that causes thw problem in tibber app?

**Comment by Isaksson** [comment] 2023-08-13 07:59
Hello.
This issue was introduced when they tried to implement proxy support in the Tibber node.
I have a fix for this, but that includes modifying the files for the Tibber node.

What you need to to is to remove or comment out the row require ('global-agent/bootstrap'); that you will find at the top in these files

tibber-data.js
tibber-feed.js
tibber-notify.js
tibber-query.js

so you have to locate this files, modify them and then restart node-RED, the location of the files depends on what system and how you installed node-RED but I could recommend to try looking at this location
~/.node-red/node_modules/node-red-contrib-tibber-api/nodes

**Comment by PowerZone21** [comment] 2023-08-13 08:37
Thanks.
I will carefully try later today.

**Comment by Isaksson** [comment] 2023-08-13 09:10
If you just verify that you modify this files then there should be no issue, if you screw things up its just to uninstall the tibber node and install it again and the files will be restored :)

**Comment by PowerZone21** [comment] 2023-08-13 11:09
Tested, and it works👏🏻👏🏻
Amazing🎉

**Comment by Isaksson** [comment] 2023-08-13 17:59
That's great 👍

**Comment by Isaksson** [comment] 2023-11-07 06:45
There is a new version of Tibber Node released that removes the proxy that is causing this issue.

**Closed as completed** 2023-11-08 17:54 UTC
